/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.AI;
import classes.Admin;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author adminccs
 */
public class MainInterface extends javax.swing.JFrame {
    
    public static DefaultListModel<String> modeloListaGanadores;

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        coronaLabelSW.setVisible(false);
        coronaLabelST.setVisible(false);
        empateLabel.setVisible(false);
        cancelLabel.setVisible(false);
        modeloListaGanadores = new DefaultListModel<>();
        ListaGanadores.setModel(modeloListaGanadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ganadoresStarWars = new javax.swing.JLabel();
        Colas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColasSW1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColasSW2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ColasSW3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ColasSW4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ganadoresStarTrek = new javax.swing.JLabel();
        Colas1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ColasST1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ColasST2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ColasST3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ColasST4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AIState = new javax.swing.JLabel();
        coronaLabelST = new javax.swing.JLabel();
        coronaLabelSW = new javax.swing.JLabel();
        cancelLabel = new javax.swing.JLabel();
        empateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        STImage = new javax.swing.JLabel();
        SWImage = new javax.swing.JLabel();
        UniquePointsSW = new javax.swing.JLabel();
        PuntosSW = new javax.swing.JLabel();
        nombrePersonajeSW = new javax.swing.JLabel();
        nombrePersonajeST = new javax.swing.JLabel();
        PuntosST = new javax.swing.JLabel();
        UniquePointsST = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ListaGanadores = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        SliderAITimer = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Star Wars");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIGHT!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Star Trek");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganadoresStarWars.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresStarWars.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresStarWars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresStarWars.setText("0");
        ganadoresStarWars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.add(ganadoresStarWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        Colas.setBackground(new java.awt.Color(0, 102, 102));
        Colas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Colas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasSW1.setBackground(new java.awt.Color(0, 0, 255));
        ColasSW1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasSW1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(ColasSW1);

        Colas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 60));

        ColasSW2.setBackground(new java.awt.Color(0, 0, 255));
        ColasSW2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasSW2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(ColasSW2);

        Colas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 60));

        ColasSW3.setBackground(new java.awt.Color(0, 0, 255));
        ColasSW3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasSW3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane4.setViewportView(ColasSW3);

        Colas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 300, 60));

        ColasSW4.setBackground(new java.awt.Color(0, 0, 255));
        ColasSW4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasSW4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane5.setViewportView(ColasSW4);

        Colas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 300, 60));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cola de refuerzo");
        Colas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Prioridad 1");
        Colas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 300, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Prioridad 2");
        Colas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 300, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Prioridad 3");
        Colas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 300, 20));

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganadoresStarTrek.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ganadoresStarTrek.setForeground(new java.awt.Color(255, 255, 255));
        ganadoresStarTrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganadoresStarTrek.setText("0");
        ganadoresStarTrek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.add(ganadoresStarTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 70));

        Colas1.setBackground(new java.awt.Color(153, 0, 153));
        Colas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Colas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColasST1.setBackground(new java.awt.Color(0, 0, 255));
        ColasST1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasST1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(ColasST1);

        Colas1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 60));

        ColasST2.setBackground(new java.awt.Color(0, 0, 255));
        ColasST2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasST2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane6.setViewportView(ColasST2);

        Colas1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 60));

        ColasST3.setBackground(new java.awt.Color(0, 0, 255));
        ColasST3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasST3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane7.setViewportView(ColasST3);

        Colas1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 300, 60));

        ColasST4.setBackground(new java.awt.Color(0, 0, 255));
        ColasST4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ColasST4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane8.setViewportView(ColasST4);

        Colas1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 300, 60));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cola de refuerzo");
        Colas1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prioridad 1");
        Colas1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 300, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Prioridad 2");
        Colas1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 300, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Prioridad 3");
        Colas1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, 300, 20));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AIState.setBackground(new java.awt.Color(255, 255, 255));
        AIState.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AIState.setForeground(new java.awt.Color(255, 255, 255));
        AIState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIState.setText("Creando colas...");
        jPanel2.add(AIState, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 35));

        coronaLabelST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rb_2012.png"))); // NOI18N
        jPanel2.add(coronaLabelST, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 132, 86));

        coronaLabelSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coronaLabelSW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rb_2012.png"))); // NOI18N
        jPanel2.add(coronaLabelSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 138, 86));

        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Cancel.png"))); // NOI18N
        jPanel2.add(cancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 420, 150));

        empateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Empate.png"))); // NOI18N
        jPanel2.add(empateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 98, 92));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vs (1).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 184, 104, 97));

        STImage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        STImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Unknown.png"))); // NOI18N
        jPanel2.add(STImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 159, 132, -1));

        SWImage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SWImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Unknown.png"))); // NOI18N
        jPanel2.add(SWImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, 132, -1));

        UniquePointsSW.setBackground(new java.awt.Color(255, 255, 255));
        UniquePointsSW.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UniquePointsSW.setForeground(new java.awt.Color(255, 255, 255));
        UniquePointsSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UniquePointsSW.setText("0");
        jPanel2.add(UniquePointsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 335, 22, -1));

        PuntosSW.setBackground(new java.awt.Color(255, 255, 255));
        PuntosSW.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosSW.setForeground(new java.awt.Color(255, 255, 255));
        PuntosSW.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PuntosSW.setText("Puntos:");
        jPanel2.add(PuntosSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 335, 60, -1));

        nombrePersonajeSW.setBackground(new java.awt.Color(255, 255, 255));
        nombrePersonajeSW.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombrePersonajeSW.setForeground(new java.awt.Color(255, 255, 255));
        nombrePersonajeSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePersonajeSW.setText("Nombre");
        jPanel2.add(nombrePersonajeSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 305, 132, 24));

        nombrePersonajeST.setBackground(new java.awt.Color(255, 255, 255));
        nombrePersonajeST.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombrePersonajeST.setForeground(new java.awt.Color(255, 255, 255));
        nombrePersonajeST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePersonajeST.setText("Nombre");
        jPanel2.add(nombrePersonajeST, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 305, 132, 24));

        PuntosST.setBackground(new java.awt.Color(255, 255, 255));
        PuntosST.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PuntosST.setForeground(new java.awt.Color(255, 255, 255));
        PuntosST.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        PuntosST.setText("Puntos:");
        jPanel2.add(PuntosST, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 335, 60, -1));

        UniquePointsST.setBackground(new java.awt.Color(255, 255, 255));
        UniquePointsST.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UniquePointsST.setForeground(new java.awt.Color(255, 255, 255));
        UniquePointsST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UniquePointsST.setText("0");
        jPanel2.add(UniquePointsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 335, 22, -1));

        jScrollPane9.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ListaGanadores.setBackground(new java.awt.Color(0, 0, 0));
        ListaGanadores.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListaGanadores.setForeground(new java.awt.Color(255, 255, 255));
        ListaGanadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ganador 1", "Ganador 2", "Ganador 3", "Ganador 4", "Ganadro 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(ListaGanadores);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 290, 80));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GANADORES");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        SliderAITimer.setBackground(new java.awt.Color(0, 0, 0));
        SliderAITimer.setForeground(new java.awt.Color(255, 0, 0));
        SliderAITimer.setMajorTickSpacing(1);
        SliderAITimer.setMaximum(10);
        SliderAITimer.setMinimum(1);
        SliderAITimer.setPaintLabels(true);
        SliderAITimer.setPaintTicks(true);
        SliderAITimer.setSnapToTicks(true);
        SliderAITimer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SliderAITimer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderAITimerStateChanged(evt);
            }
        });
        jPanel2.add(SliderAITimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 390, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Velocidad de la batalla (seg)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Colas, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Colas1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Colas1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Colas, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderAITimerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderAITimerStateChanged
        AI.time = SliderAITimer.getValue();
    }//GEN-LAST:event_SliderAITimerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
        
         // Crear instancias de las clases necesarias
        Admin admin = new Admin();
        AI ai = new AI();

        // Inicializar personajes y colocarlos en las colas
        admin.initializeCharacters();
        
        // Simular rondas de la IA
        for (int round = 1; round <= 1000; round++) { // Ejemplo: 1000 rondas
            System.out.println("\n--- Ronda " + round + " ---");

            // Mostrar las colas antes de la ronda
            admin.printQueues();

            // Seleccionar personajes para el combate desde las colas
            classes.Character[] charactersForBattle = admin.selectCharactersForBattle();
            classes.Character starWarsCharacter = charactersForBattle[0];
            classes.Character starTrekCharacter = charactersForBattle[1];

            if (starWarsCharacter != null && starTrekCharacter != null) {
                System.out.println("Inicia el combate: " + starWarsCharacter.getName() + " vs " + starTrekCharacter.getName());
            }
            // Mostrar las colas en la interfaz
            admin.actualizarColasEnInterfaz();

            // Procesar la batalla en la IA
            ai.processBattle(starWarsCharacter, starTrekCharacter);

            // Actualizar las colas después de la ronda
//            admin.updateQueues(); ESTO HACE QUE SE SUBAN LAS POSICIONES 1 DE LAS COLAS AL FINAL DE CADA RONDA.
        }

        // Mostrar las colas al final de la simulación
        System.out.println("\n--- Colas finales ---");
        admin.printQueues();
        admin.actualizarColasEnInterfaz();
       
    }
    
    public static void setDefStats() {
        if (SWImage != null && STImage != null) {
            SWImage.setIcon(new ImageIcon("src\\imgs\\question.jpg"));
            STImage.setIcon(new ImageIcon("src\\imgs\\question.jpg"));
            nombrePersonajeSW.setText("Buscando oponente...");
            nombrePersonajeST.setText("Buscando oponente...");
            UniquePointsSW.setText("0");
            UniquePointsST.setText("0");

        } else {
            System.out.println("La imagen de Star Wars o la imagen de Star Trek es null. Asegúrate de que estén inicializados correctamente.");
        }
    }
    
    public static void setStarWarsIcon(String name, int power) {
        SWImage.setIcon(new ImageIcon("src\\imgs\\StarWars\\" + name + ".png"));
        nombrePersonajeSW.setText(name);
        UniquePointsSW.setText(Integer.toString(power));
    }

    public static void setStarTrekIcon(String name, int power) {
        STImage.setIcon(new ImageIcon("src\\assets\\StarTrek\\" + name + ".png"));
        nombrePersonajeST.setText(name);
        UniquePointsST.setText(Integer.toString(power));
    }
    
    public static JLabel getGanadoresST() {
        return ganadoresStarTrek;
    }

    public static void setGanadoresST(JLabel ganadoresST) {
        MainInterface.ganadoresStarTrek = ganadoresST;
    }

    public static JLabel getGanadoresSW() {
        return ganadoresStarWars;
    }

    public static void setGanadoresSW(JLabel ganadoresSW) {
        MainInterface.ganadoresStarWars = ganadoresSW;
    }

    
     public static void marcadorStarWars(int puntaje) {
        ganadoresStarWars.setText(Integer.toString(puntaje));
    }

    public static void marcadorStarTrek(int puntaje) {
        ganadoresStarTrek.setText(Integer.toString(puntaje));
    }
    
    
     // Método para colocar la corona sobre la imagen del personaje ganador
    public static void setCoronaPositionStarWars(JLabel characterImage) {
        coronaLabelSW.setVisible(true);
    }

    public static void setCoronaPositionStarTrek(JLabel characterImage) {
        coronaLabelST.setVisible(true);
    }
    
    public static void setDrawVisible() {
        empateLabel.setVisible(true);
    }
    
    public static JLabel getEmpateLabel() {
        return empateLabel;
    }
    
    public static JLabel getCancelLabel() {
        return cancelLabel;
    }

    public static void setCancelVisible() {
        cancelLabel.setVisible(true);
    }
    
    public static void setNombreSW(String name) {
        nombrePersonajeSW.setText(name);
    }

    public static void setNombreST(String name) {
        nombrePersonajeST.setText(name);
    }
    
    public static JLabel getColasStarWars(int index) {
        switch (index) {
            case 1:
                return ColasSW1;
            case 2:
                return ColasSW2;
            case 3:
                return ColasSW3;
            case 4:
                return ColasSW4;
            default:
                return null;
        }
    }

    public static JLabel getColasStarTrek(int index) {
        switch (index) {
            case 1:
                return ColasST1;
            case 2:
                return ColasST2;
            case 3:
                return ColasST3;
            case 4:
                return ColasST4;
            default:
                return null;
        }
    }
    
    public static JLabel getSTImage() {
        return STImage;
    }

    public static void setSTImage(JLabel STImage) {
        MainInterface.STImage = STImage;
    }

    public static JLabel getSWIMG() {
        return SWImage;
    }

    public static void setSWImage(JLabel SWImage) {
        MainInterface.SWImage = SWImage;
    }

    public static JLabel getUniquePointsST() {
        return UniquePointsST;
    }

    public static void setUniquePointsST(JLabel UniquePointsST) {
        MainInterface.UniquePointsST = UniquePointsST;
    }

    public static JLabel getUniquePointsSW() {
        return UniquePointsSW;
    }

    public static void setUniquePointsSW(JLabel UniquePointsSW) {
        MainInterface.UniquePointsSW = UniquePointsSW;
    }

    public static JLabel getNombreST() {
        return nombrePersonajeST;
    }

    public static void setNombreST(JLabel nombrePersonajeST) {
        MainInterface.nombrePersonajeST = nombrePersonajeST;
    }

    public static JLabel getNombreSW() {
        return nombrePersonajeSW;
    }

    public static void setNombreSW(JLabel nombrePersonajeSW) {
        MainInterface.nombrePersonajeSW = nombrePersonajeSW;
    }

    public static JLabel getColasST1() {
        return ColasST1;
    }

    public static void setColasST1(JLabel ColasST1) {
        MainInterface.ColasST1 = ColasST1;
    }

    public static JLabel getColasSW1() {
        return ColasSW1;
    }

    public static void setColasSW1(JLabel ColasSW) {
        MainInterface.ColasSW1 = ColasSW;
    }

    public static JLabel getColasST2() {
        return ColasST2;
    }

    public static void setColasST2(JLabel ColasST2) {
        MainInterface.ColasST2 = ColasST2;
    }

    public static JLabel getColasST3() {
        return ColasST3;
    }

    public static void setColasST3(JLabel ColasST3) {
        MainInterface.ColasST3 = ColasST3;
    }

    public static JLabel getColasST4() {
        return ColasST4;
    }

    public static void setColasST4(JLabel ColasST4) {
        MainInterface.ColasST4 = ColasST4;
    }

    public static JLabel getColasSW2() {
        return ColasSW2;
    }

    public static void setColasSW2(JLabel ColasSW2) {
        MainInterface.ColasSW2 = ColasSW2;
    }

    public static JLabel getColasSW3() {
        return ColasSW3;
    }

    public static void setColasSW3(JLabel ColasSW3) {
        MainInterface.ColasSW3 = ColasSW3;
    }

    public static JLabel getColasSW4() {
        return ColasSW4;
    }

    public static void setColasSW4(JLabel ColasSW4) {
        MainInterface.ColasSW4 = ColasSW4;
    }
    
    public static void agregarGanador(String elemento) {
        modeloListaGanadores.addElement(elemento);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel AIState;
    private javax.swing.JPanel Colas;
    private javax.swing.JPanel Colas1;
    public static javax.swing.JLabel ColasST1;
    public static javax.swing.JLabel ColasST2;
    public static javax.swing.JLabel ColasST3;
    public static javax.swing.JLabel ColasST4;
    public static javax.swing.JLabel ColasSW1;
    public static javax.swing.JLabel ColasSW2;
    public static javax.swing.JLabel ColasSW3;
    public static javax.swing.JLabel ColasSW4;
    public static javax.swing.JList<String> ListaGanadores;
    public static javax.swing.JLabel PuntosST;
    public static javax.swing.JLabel PuntosSW;
    public static javax.swing.JLabel STImage;
    public static javax.swing.JLabel SWImage;
    private javax.swing.JSlider SliderAITimer;
    public static javax.swing.JLabel UniquePointsST;
    public static javax.swing.JLabel UniquePointsSW;
    public static javax.swing.JLabel cancelLabel;
    public static javax.swing.JLabel coronaLabelST;
    public static javax.swing.JLabel coronaLabelSW;
    public static javax.swing.JLabel empateLabel;
    public static javax.swing.JLabel ganadoresStarTrek;
    public static javax.swing.JLabel ganadoresStarWars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JLabel nombrePersonajeST;
    public static javax.swing.JLabel nombrePersonajeSW;
    // End of variables declaration//GEN-END:variables
}
